### ISSUE TITLE
Error in check_rebuild is understood as no need to rebuild

### ISSUE THREAD

**Issue by spalladino** [AztecProtocol/build-system#3]
The check_rebuild script returns 0 to trigger a rebuild, 1 for not. In the event of an error in the script (eg diffing vs a commit that is not available), it returns non-zero to the `build` script, so no rebuild is triggered and the old version is tagged as the `last_successful_commit`.

As a workaround, we can mark the image as `tainted` to force a rebuild and sidestep this issue. This can be manually on the registry, or if we don't have access, adding a temporary step to the CI to do it, replacing the commit hash and image name with the one you're dealing with:

```
      - run:
          name: "Taint"
          command: "tag_remote_image aztec3-circuits-wasm-linux-clang cache-7222e17fae73c3d932110e3df55500f1479ddb34 tainted"
```

**Comment by cheethas** [comment]
Commenting as i think this is addressed by https://github.com/AztecProtocol/build-system/pull/5 ?
